In [29]:
# External function
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def num_der(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]

        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)

        x[idx] = tmp_val - delta_x
        fx2 = f(x)

        grad[idx] = (fx1 - fx2) / (2*delta_x)
        x[idx] = tmp_val
        it.iternext()
    
    return grad

In [30]:
# LogicGate Class
class LogicGate:
    
    def __init__(self, gate_name, xdata, tdata):
        self.name = gate_name
        
        # 입력과 출력 데이터 크기 조정
        self.__xdata = xdata.reshape(4, 2)
        self.__tdata = tdata.reshape(4, 1)

        # 입력층-은닉층의 가중치와 바이어스 초기화
        # 6개의 노드로 가정하였다.
        self.__W2 = np.random.rand(2, 6)
        self.__b2 = np.random.rand(6)

        # 은닉층-출력층의 가중치와 바이어스 초기화
        self.__W3 = np.random.rand(6, 1)
        self.__b3 = np.random.rand(1)

        # 학습률 초기화
        self.learning_rate = 1e-2

        print("\n" + self.name + " object is created!\n")

    def feed_forword(self):
        delta = 1e-7  # 무한대 발산 방지

        z2 = np.dot(self.__xdata, self.__W2) + self.__b2
        a2 = sigmoid(z2)

        z3 = np.dot(a2, self.__W3) + self.__b3
        y = a3 = sigmoid(z3)

        return -np.sum( self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta) )

    
    def loss_val(self):
        delta = 1e-7

        z2 = np.dot(self.__xdata, self.__W2) + self.__b2
        a2 = sigmoid(z2)

        z3 = np.dot(a2, self.__W3) + self.__b3
        y = a3 = sigmoid(z3)

        return -np.sum( self.__tdata*np.log(y+delta) + (1-self.__tdata)*np.log((1-y)+delta) )

    def train(self):
        f = lambda x : self.feed_forword()

        print("Initial loss value = " , self.loss_val())

        for step in range(10001):

            self.__W2 -= self.learning_rate * num_der(f, self.__W2)
            self.__b2 -= self.learning_rate * num_der(f, self.__b2)
            self.__W3 -= self.learning_rate * num_der(f, self.__W3)
            self.__b3 -= self.learning_rate * num_der(f, self.__b3)

            if (step % 1000 == 0):
                print("step = ", step, "  loss value = ", self.loss_val())

    def predict(self, xdata):
        z2 = np.dot(xdata, self.__W2) + self.__b2
        a2 = sigmoid(z2)

        z3 = np.dot(a2, self.__W3) + self.__b3
        y = sigmoid(z3)

        if y > 0.5:
            result = 1
        else:
            result = 0
        
        return y, result

In [31]:
# Usage
xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
AND_tdata = np.array([0, 0, 0, 1])
OR_tdata = np.array([0, 1, 1, 1])
NAND_tdata = np.array([1, 1, 1, 0])
XOR_tdata = np.array([0, 1, 1, 0])

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

# AND gate
AND_obj = LogicGate("AND_GATE", xdata, AND_tdata)
AND_obj.train()

for data in test_data:
    print(AND_obj.predict(data))

# OR gate
OR_obj = LogicGate("OR_GATE", xdata, OR_tdata)
OR_obj.train()

for data in test_data:
    print(OR_obj.predict(data))

# NAND gate
NAND_obj = LogicGate("NAND_GATE", xdata, NAND_tdata)
NAND_obj.train()

for data in test_data:
    print(NAND_obj.predict(data))

# XOR gate
XOR_obj = LogicGate("XOR_GATE", xdata, XOR_tdata)
XOR_obj.train()

for data in test_data:
    print(XOR_obj.predict(data))


AND_GATE object is created!

Initial loss value =  6.351847171020783
step =  0   loss value =  6.095722954335691
step =  1000   loss value =  1.8104469183365102
step =  2000   loss value =  0.9076065588470372
step =  3000   loss value =  0.42736684055714014
step =  4000   loss value =  0.23113030523946865
step =  5000   loss value =  0.14525194077794842
step =  6000   loss value =  0.10156491594687483
step =  7000   loss value =  0.07632583687308526
step =  8000   loss value =  0.06030164912965123
step =  9000   loss value =  0.04939399070568784
step =  10000   loss value =  0.04156860151372238
(array([4.69241903e-05]), 0)
(array([0.01018737]), 0)
(array([0.01047066]), 0)
(array([0.97945733]), 1)

OR_GATE object is created!

Initial loss value =  2.2726112403794763
step =  0   loss value =  2.2666958453780706
step =  1000   loss value =  1.6892564756758655
step =  2000   loss value =  0.8685102505227316
step =  3000   loss value =  0.3959125647526865
step =  4000   loss value =  0.216