In [23]:
import numpy as np

x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7]])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)

print("x_data shape = ", x_data.shape, " t_data shape = ", t_data.shape)

x_data shape =  (9, 2)  t_data shape =  (9, 1)


In [24]:
W = np.random.rand(2, 1)
b = np.random.rand(1)

print("W = ", W, "b = ", b, "\nW shape = ", W.shape, "b shape = ", b.shape)

W =  [[0.7832882 ]
 [0.78623089]] b =  [0.25020113] 
W shape =  (2, 1) b shape =  (1,)


In [25]:
def sigmoid(z):
    return 1 / ( 1 + np.exp(-z) )

In [26]:
def loss_func(x, t):
    delta = 1e-7

    z = np.dot(x, W) + b
    y = sigmoid(z)

    return -np.sum( t*np.log(y+delta) + (1-t)*np.log((1-y)+delta) )

In [27]:
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])

    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)

        x[idx] = tmp_val - delta_x
        fx2 = f(x)

        grad[idx] = (fx1 - fx2) / (2*delta_x)
        x[idx] = tmp_val
        it.iternext()
    
    return grad

In [28]:
def error_val(x, t):
    delta = 1e-7

    z = np.dot(x, W) + b
    y = sigmoid(z)

    return -np.sum( t*np.log(y+delta) + (1-t)*np.log((1-y)+delta) )

In [29]:
def predict(x):
    z = np.dot(x, W) + b
    y = sigmoid(z)

    if y > 0.5:
        result = 1
    else:
        result = 0
    
    return y, result

In [33]:
learning_rate = 1e-2

f = lambda x : loss_func(x_data, t_data)

print("[Initial]\nerror value = ", error_val(x_data, t_data), "W = ", W, "b = ", b)

print("\n[Process]")
for step in range(80001):

    W -= learning_rate * numerical_derivative(f, W)
    b -= learning_rate * numerical_derivative(f, b)

    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, "b = ", b)

[Initial]
error value =  0.0722779240550795 W =  [[2.28922327]
 [1.06806688]] b =  [-26.92539848]

[Process]
step =  0 error value =  0.07227707828727678 W =  [[2.28923021]
 [1.06807175]] b =  [-26.92549009]
step =  400 error value =  0.07194034249537287 W =  [[2.29200072]
 [1.07001242]] b =  [-26.96204701]
step =  800 error value =  0.07160671269357571 W =  [[2.29475859]
 [1.07194384]] b =  [-26.9984349]
step =  1200 error value =  0.07127614628029709 W =  [[2.29750395]
 [1.07386608]] b =  [-27.03465529]
step =  1600 error value =  0.07094860142699352 W =  [[2.30023691]
 [1.07577923]] b =  [-27.07070971]
step =  2000 error value =  0.07062403706081963 W =  [[2.30295758]
 [1.07768339]] b =  [-27.10659967]
step =  2400 error value =  0.0703024128476475 W =  [[2.30566606]
 [1.07957862]] b =  [-27.14232665]
step =  2800 error value =  0.06998368917557049 W =  [[2.30836248]
 [1.08146502]] b =  [-27.17789211]
step =  3200 error value =  0.06966782713887543 W =  [[2.31104692]
 [1.08334267]] 

In [31]:
test_data = np.array([13, 9])
(real_val, logical_val) = predict(test_data)
print(real_val, logical_val)

[0.93500274] 1


In [34]:
test_data = np.array([5, 8])
print(predict(test_data))

(array([0.00034816]), 0)


In [35]:
test_data = np.array([7, 21])
print(predict(test_data))

(array([0.99999964]), 1)


In [36]:
test_data = np.array([12, 0])
print(predict(test_data))

(array([0.52357824]), 1)
